remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Identifying Affected Libraries and Their Ecosystems for Open Source Software Vulnerabilities]
description: [This paper has been submitted to ICSE 2024.]