GROUNDTRUTH_PATH = "../../ground_truth/pypimavennpmgo_component_tagging_2023_0720_wss.xlsx"
CVE_INIT_PATH = "./iterrate_process/inputclue_init.json"
REPO_INIT_PATH = "./iterrate_process/softwarename2componentdb.json"
General_Bug_Clue_Depth1_Path = "./iterrate_process/generalbug_clue_depth1.json"
General_Bug_Clue_Depth2_Path = "./iterrate_process/generalbug_clue_depth2.json"
Ref_Round_0 = "./iterrate_process/cve_refs.json"
Ref_Round_1 = "./iterrate_process/layer1_refs.json"
Ref_Round_2 = "./iterrate_process/layer2_refs.json"

Ref2RepoPath = "./iterrate_process/ref2repo.json"
Jenkins2RepoPath = "./iterrate_process/jenkinsplugin2repo.json"
Component_DB_1 = "./iterrate_process/componentdb_1.json"
Component_DB_2 = "./iterrate_process/componentdb_2.json"
Component_DB_3 = "./iterrate_process/componentdb_3.json"

Componentdb_Patch_Issue = "./iterrate_process/component_refs_depth1.json"
Componentdb_Patch_Layer2 = "./iterrate_process/component_refs_depth2.json"
Componentdb_Patch_Layer3 = "./iterrate_process/component_refs_depth3.json"
Component_Clue = "./iterrate_process/componentdb_clue_depth1.json"
Component_Clue_2 = "./iterrate_process/componentdb_clue_depth2.json"
Component_Clue_3 = "./iterrate_process/componentdb_clue_depth3.json"
Patch_Cache_Path = "./log/patch_cache.json"
Api_Cache_Path = "./log/api_cache.json"
Commit_Api_Cache_Path = "./log/commit_api_cache.json"
